apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
  namespace: book
  labels:
    app: book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      name: book-api
      labels:
        app: book-api
    spec:
      containers:
        - name: book-api
          image: mariia5345/readsphere_book-api:latest
          env:
            - name: DATABASE_CONNECTION_STRING
              value: Host=postgres-service.book.svc.cluster.local;Port=5432;Database=book-api-db;Username=admin;Password=admin
            - name: RABBITMQ_HOST
              value: rabbitmq3.default.svc.cluster.local
            - name: RABBITMQ_USER
              value: user
            - name: RABBITMQ_PASSWORD
              value: password
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 443
              protocol: TCP
      restartPolicy: Always      
      imagePullSecrets:
        - name: regcred       