apiVersion: v1
kind: Service
metadata:
  name: book-api
  namespace: book
  labels:
    app: book-api
spec:
  type: ClusterIP
  selector:
    app: book-api
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443