apiVersion: v1
kind: Service
metadata:
  name: book-api-service
  labels:
    app: book-api
spec:
  type: ClusterIP
  selector:
    app: book-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 443